name: SAP Pipeline helper

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:

      - name: Command help
        uses: SAP/project-piper-action@master
        with:
          command: help
        
