name: SAP Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ATC checks
        uses: SAP/project-piper-action@master
        with:
          command: atcCheck
          endpoint: ${{ secrets.SAP_ENDPOINT }}
          client: ${{ secrets.SAP_CLIENT }}
          user: ${{ secrets.SAP_USER }}
          password: ${{ secrets.SAP_PASSWORD }}

      - name: Run AUnit tests
        uses: SAP/project-piper-action@master
        with:
          command: aunitRun
          endpoint: ${{ secrets.SAP_ENDPOINT }}
          client: ${{ secrets.SAP_CLIENT }}
          user: ${{ secrets.SAP_USER }}
          password: ${{ secrets.SAP_PASSWORD }}
